### ISSUE TITLE
Add mock user JWT

### ISSUE THREAD

**Issue by gr4per** [OpusCapitaBusinessNetwork/nginx-rp#2]
To avoid having to add
kong, user, auth, postgres to every docker compose for development
we assume it is fair enough to use nginx-rp with same forwarding rules as kong, and injecting user claims into the request via X_USER_CLAIMS header.
This can be used to develop application with static user

**Comment by gr4per** [comment]
Let's also add feature to allow overriding it at runtime.
Possible approach: 
add static html page to :8080/index.html
This should contain a simple html form for the claims to be edited
Then submit should actually not post to server but just set it as cookie

Put the default claims into nginx-rp docker image, as json on index.html.
we could easily predefine the std users
scott.tiger@example.com -> user, supplier-admin
john.doe@ncc.com -> user, customer-admin
ocadmin@opuscapita.com -> user, admin

**Comment by sureshvarman-cronj** [comment]
added mocking JWT using consul KV store. https://github.com/OpusCapita/nginx-rp/pull/3
